alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: pctf-ctfd
region: blr
services:
- envs:
  - key: UPLOAD_PROVIDER
    scope: RUN_AND_BUILD_TIME
    value: s3
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: AWS_S3_BUCKET
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: WORKERS
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: TIMEOUT
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: 
  - key: REVERSE_PROXY
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: AWS_S3_ENDPOINT_URL
    scope: RUN_AND_BUILD_TIME
    value: https://sgp1.digitaloceanspaces.com
  http_port: 8080
  image:
    registry_type: DOCR
    repository: ctfd
    tag: email
  instance_count: 6
  instance_size_slug: professional-xs
  name: pctf-ctfd
  routes:
  - path: /
  source_dir: /
