version: '3.8'

services:
  ctfd:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: registry.digitalocean.com/pragyan-registry/ctfd
    user: root
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd

    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=FcN2pgoYdnk1wo4A6GUlEXHqSmaL8CSZqmr5nIPj57kAnjl1KL
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=FcN2pgoYdnk1wo4A6GUlEXHqSmaL8CSZqmr5nIPj57kAnjl1KL
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    # networks:
    #     internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    command: redis-server --requirepass Qfqp9ZzT9ySotMDziyZcOMtgXkLWPHMOf6F75thKdRbzRTIQhu
    volumes:
    - .data/redis:/data
    # networks:
    #     internal:

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 9091:80
    depends_on: 
      - db
    environment:
      - PMA_HOST=db


networks:
   default:
   internal:
       internal: true
